# Docker Compose override file for security-patched Zammad
# Use with: docker compose -f docker-compose.yml -f docker-compose.security.yml up -d

version: "3.8"

services:
  # Override the zammad services to use patched base image
  zammad-backup:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    read_only: false
    tmpfs:
      - /tmp
      - /run

  zammad-init:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

  zammad-nginx:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  zammad-railsserver:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
      - /app/tmp

  zammad-scheduler:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

  zammad-websocket:
    image: vantagepointconsult/zammad:6.5.1-secure
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

  # Additional security configurations for other services
  zammad-postgresql:
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_INITDB_ARGS: "--auth-local=md5 --auth-host=scram-sha-256"
    
  zammad-redis:
    security_opt:
      - no-new-privileges:true
    command: redis-server --requirepass ${REDIS_PASSWORD:-zammad_redis_pass_change_me}
    
  zammad-memcached:
    security_opt:
      - no-new-privileges:true
    command: memcached -m 256M -I 2m
    
  zammad-elasticsearch:
    security_opt:
      - no-new-privileges:true
    environment:
      # Additional Elasticsearch security settings
      xpack.security.enabled: 'false'
      xpack.security.http.ssl.enabled: 'false'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: ${ELASTICSEARCH_JAVA_OPTS:--Xms1g -Xmx1g}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
